library(ISLR)
library(RARR)
a <- Standardized_Residuals(Sales~., Carseats)
b <- Studentized_Residuals(Sales~., Carseats)
c <- Press_and_R2(Sales~., Carseats)
d <- Studentized_Press_Residuals(Sales~., Carseats)
e <- R_Student_Residuals(Sales~., Carseats)
f <- normal_plot(Sales~., Carseats, 3)
g <- resid_fitted_plot(Sales~., Carseats)
h <- resid_regres_plot(Sales~., Carseats, 1)
i <- Robust_influence(0.2, 'Huber', 2)
j <- IRLS(Sales~., Carseats, state = 'Huber', t=2)
